---
title: "patch family surface transfer balances: turfgrass and tree 2 stratum"
date: "2023-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(lubridate)
library(RHESSysIOinR)
source("/Volumes/GoogleDrive/My Drive/help_with_rhessys/watbal.R")
library(here)
dir = "out/msr_on_2strat"
```


```{r basin, echo=FALSE}

wb_bas = readr::read_delim(here(dir,"bas.csv")) 

watbal = wb_bas %>% 
  dplyr::filter(year==1995) %>% 
  group_by(date, veg_area, irr) %>% 
  summarize(balance = mean(watbal)) 

ggplot(watbal) + geom_point(aes(x=date, y=balance)) + ggtitle("basin water balance") + facet_grid(irr~veg_area)

```

turfgrass parameters that were set up using just single patch of turfgrass and irrigation

- did not balance with sharing on and oak tree
- sharing with pavement does balance  - more water input from surface transfer, no rz transfer  


#### paved patch fam: 50% turfgrass, 50% pavement 

patchIDs:

- 60853701 = two stratum: turfgrass and tree 
- 60853702 = pavement

```{r patch, echo=FALSE}
wb_p = readr::read_delim(here(dir,"pat.csv")) 

patchout = wb_p %>% group_by(year, veg_area, patchID, irr, grasstype) %>% summarise_all(mean)

# plot boxplots 
ggplot(patchout) + geom_boxplot(aes(x=as.factor(patchID), y=surface_transfer, col=as.factor(veg_area))) + facet_grid(veg_area~irr)

ggplot(patchout) + geom_boxplot(aes(x=as.factor(patchID), y=rz_storage, col=as.factor(veg_area))) + facet_grid(veg_area~irr)

ggplot(patchout) + geom_boxplot(aes(x=as.factor(patchID), y=unsat_storage, col=as.factor(veg_area))) + facet_grid(veg_area~irr)

ggplot(patchout) + geom_boxplot(aes(x=as.factor(patchID), y=streamflow, col=as.factor(veg_area))) + facet_grid(veg_area~irr)

ggplot(patchout) + geom_boxplot(aes(x=as.factor(patchID), y=evap, col=as.factor(veg_area))) + facet_grid(veg_area~irr)

ggplot(patchout) + geom_boxplot(aes(x=as.factor(patchID), y=rootzone.S, col=as.factor(veg_area))) + facet_grid(veg_area~irr)

ggplot(patchout) + geom_boxplot(aes(x=as.factor(patchID), y=rootzone.field_capacity, col=as.factor(veg_area))) + facet_grid(veg_area~irr)


```

#### stratum output 

```{r msr, echo=FALSE}

strat = readr::read_delim(here(dir, "strat.csv"))


stratout = strat %>% 
  group_by(year, veg_area, veg_parm_ID, irr, grasstype) %>% 
  summarise_all(mean) %>% 
  mutate(id = factor(veg_parm_ID, 
                     levels = c(11, 3, 1), 
                     labels=c("tree", "turfgrass","no veg"))) %>% 
  dplyr::filter(veg_parm_ID > 1)
  
ggplot(stratout) + geom_boxplot(aes(x=veg_area, y=epv.proj_lai, col=irr)) + facet_grid('id', scales="free")

ggplot(stratout) + geom_boxplot(aes(x=veg_area, y=epv.height, col=irr)) + facet_grid('id', scales="free")

ggplot(stratout) + geom_boxplot(aes(x=veg_area, y=rootzone.depth, col=irr)) + facet_grid('id', scales="free")

ggplot(stratout) + geom_boxplot(aes(x=veg_area, y=cs.totalc, col=irr)) + facet_grid('id', scales="free")

ggplot(stratout) + geom_boxplot(aes(x=veg_area, y=trans, col=irr)) + facet_grid('id', scales="free")

ggplot(stratout) + geom_boxplot(aes(x=veg_area, y=cdf.psn_to_cpool, col=irr)) + facet_grid('id', scales="free")

ggplot(stratout) + geom_boxplot(aes(x=veg_area, y=npp, col=irr)) + facet_grid('id', scales="free")
```



